kind: Service
apiVersion: v1
metadata:
  name: service-backend
  namespace: roadguard

spec:
  selector:
    app: backend

  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: "TCP"
